with full_users as ((select user_tracking_id, 
  user_email,
  user_id, 
  user_registered, 
  first_name,  last_name, 
  billing_phone, billing_city, billing_state, 
  billing_country, 
  billing_postcode, 
  shipping_city, shipping_state, shipping_country, shipping_postcode, 
  trial_date_start, 
  cast(_schedule_trial_end as date) as _schedule_trial_end, cast(_schedule_cancelled as date) _schedule_cancelled, cast(_schedule_next_payment as date) as _schedule_next_payment, 
  billing_cycles,
  current_status, 
  full_order_id, 
  first_product_id as first_order_id, latest_product_id as latest_order_id, 
	first_mktg_custom_1, first_mktg_custom_2, 
	latest_mktg_custom_1, latest_mktg_custom_2,
  first_aff_id, latest_aff_id,
  total_amount, 
  order_shipping, order_tax, 
  products_purchased, 
  member_revenue, 
  ecommerce_revenue, 
  number_orders,
  type_customers, 
  'no' as alpha_testers, 
	'woocommerce' as crm_platform
  from  {{ ref('users_pivot_woo') }} )
UNION ALL
  (select cast(user_tracking_id as string) as user_tracking_id, 
  user_email, 
  user_id, 
  cast(NULLIF(user_registered,'') as timestamp) as user_registered,
  first_name, last_name, 
  billing_phone, billing_city, billing_state, 
  billing_country, 
  billing_postcode, 
  shipping_city, shipping_state, shipping_country, shipping_postcode,
  trial_date_start, 
  _schedule_trial_end, _schedule_cancelled, _schedule_next_payment, 
  billing_cycles,
  current_status, 
  full_order_id, 
  first_order_id, latest_order_id, 
	first_mktg_custom_1, first_mktg_custom_2, 
	latest_mktg_custom_1, latest_mktg_custom_2,
  cast(first_aff_id as string) as first_aff_id, 
  cast(latest_aff_id as string) as latest_aff_id,
  total_amount, 
  order_shipping, order_tax, 
  products_purchased, 
  member_revenue, 
  ecommerce_revenue,
  number_orders, 
  type_customers, 
  'no' as alpha_testers, 
	'konnektive' as crm_platform
  from  {{ ref('users_pivot_kon') }} ))

select distinct * from full_users